# Generated by Django 6.0.5 on 2026-05-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='会社名')),
                ('status', models.CharField(choices=[('considering', '検討中'), ('applied', '応募済み'), ('document_screening', '書類選考'), ('interview', '面接'), ('offer', '内定'), ('rejected', '不採用'), ('declined', '辞退')], default='considering', max_length=30, verbose_name='応募ステータス')),
                ('memo', models.TextField(blank=True, verbose_name='メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
            ],
            options={
                'verbose_name': '会社',
                'verbose_name_plural': '会社',
                'ordering': ['-created_at'],
            },
        ),
    ]
