# Generated by Django 6.0.5 on 2026-05-06 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_split_memos'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='has_interview',
            field=models.BooleanField(default=False, verbose_name='面接予定がある'),
        ),
        migrations.AddField(
            model_name='company',
            name='interview_date',
            field=models.DateField(blank=True, null=True, verbose_name='面接日'),
        ),
        migrations.AddField(
            model_name='company',
            name='interview_format',
            field=models.CharField(blank=True, choices=[('online', 'オンライン'), ('in_person', '対面'), ('phone', '電話'), ('other', 'その他')], max_length=20, verbose_name='面接形式'),
        ),
        migrations.AddField(
            model_name='company',
            name='interview_time',
            field=models.TimeField(blank=True, null=True, verbose_name='面接時間'),
        ),
    ]
